FROM node:20-bullseye

# install build dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    bash \
    curl \
    git \
    nano \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

EXPOSE 3000

RUN mkdir /workspace

CMD [ "node", "server.js" ]