# Stage 1: Build the frontend image
FROM node:20-alpine As frontend_builder

WORKDIR /app

COPY ./frontend/package*.json /app

RUN npm install

COPY ./frontend /app

RUN npm run build 

# Stage 2: Build the fullstack image
FROM node:20-alpine

WORKDIR /app

COPY ./backend/package*.json /app

RUN npm install

COPY ./backend /app

COPY --from=frontend_builder /app/dist /app/public

CMD [ "node", "server.js" ]

